#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
JSON schemas for configuration validation.

Schema files are auto-generated by config/validation.py on import.
"""

# This file is required for Python to treat the schemas directory as a package
